{"name": "Получение заказов пользователя если пользователь не авторизовался", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestGeOrders' object has no attribute 'client'", "trace": "self = <tests.test_get_orders_list.TestGeOrders object at 0x04D29610>\n\n    @allure.title(\"Получение заказов пользователя если пользователь не авторизовался\")\n    def test_get_order_user_not_auth(self):\n    \n>       response = self.client.get(API_ENDPOINTS[\"create_order\"], Ingredients.correct_ingredients_data)\nE       AttributeError: 'TestGeOrders' object has no attribute 'client'\n\ntests\\test_get_orders_list.py:24: AttributeError"}, "start": 1740399507186, "stop": 1740399507186, "uuid": "ff8f67d2-942e-4f88-88da-f4dc7e5068e6", "historyId": "a51bc8753d4f857c0117a131349533d4", "testCaseId": "a51bc8753d4f857c0117a131349533d4", "fullName": "tests.test_get_orders_list.TestGeOrders#test_get_order_user_not_auth", "labels": [{"name": "suite", "value": "Получение доступных заказов по пользователю"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestGeOrders"}, {"name": "host", "value": "LAPTOP-JTVFLPC5"}, {"name": "thread", "value": "14732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_orders_list"}]}