{"name": "не существующий пользователь не может авторизоваться", "status": "passed", "start": 1740397612428, "stop": 1740397613033, "uuid": "8ed1ef79-f63a-4dbb-a674-e1d0d5c5cff4", "historyId": "5197e7c5b3964a8af0f84e0118a7acc4", "testCaseId": "5197e7c5b3964a8af0f84e0118a7acc4", "fullName": "tests.test_login_user.TestLoginUser#test_login_incorrect_credentials", "labels": [{"name": "suite", "value": "Логин пользователя"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "LAPTOP-JTVFLPC5"}, {"name": "thread", "value": "18516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}