{"name": "не существующий пользователь не может авторизоваться", "status": "passed", "start": 1740399624307, "stop": 1740399625087, "uuid": "eb579cc3-cef8-4ae1-a634-c24813afa279", "historyId": "5197e7c5b3964a8af0f84e0118a7acc4", "testCaseId": "5197e7c5b3964a8af0f84e0118a7acc4", "fullName": "tests.test_login_user.TestLoginUser#test_login_incorrect_credentials", "labels": [{"name": "suite", "value": "Логин пользователя"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "LAPTOP-JTVFLPC5"}, {"name": "thread", "value": "6028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}